
<h3>LIST OF ALL ALBUMS</h3>

<table>
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($this->all as $album) : ?>
<tr>
    <td><?php echo $this->escape($album->title);?></td>
    <td><?php echo $this->escape($album->artist);?></td>
    <td>
        <a href="/Index/edit">Edit</a>
        <a href="/Index/delete">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>